name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure and build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run unit tests
      run: |
        cd build/test
        ./events_test
